version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: postgres_auth_db
    environment:
      POSTGRES_DB: authbase
      POSTGRES_USER: def_user
      POSTGRES_PASSWORD: def_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: